workspace(name = "helloworld")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Depend on com_google_protobuf (a bazel project)
http_archive(
      name = "com_google_protobuf",
      url = "https://github.com/protocolbuffers/protobuf/archive/refs/tags/v21.5.tar.gz",
      sha256 = "4a7e87e4166c358c63342dddcde6312faee06ea9d5bb4e2fa87d3478076f6639",
      strip_prefix = "protobuf-21.5",
)
load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")
protobuf_deps()

# Depend on arrayfire (a non-bazel projec, built using CMake - in 3rdparty/arrayfire.BUILD)
_ALL_CONTENT = """\
filegroup(
    name = "all_srcs",
    srcs = glob(["**"]),
    visibility = ["//visibility:public"],
)
"""
http_archive(
      name = "arrayfire",
      build_file_content = _ALL_CONTENT,
      sha256 = "2d01b35adade2433078f57e2233844679aabfdb06a41e6992a6b27c65302d3fe",
      strip_prefix = "arrayfire-full-3.8.2",
      urls = ["https://github.com/arrayfire/arrayfire/releases/download/v3.8.2/arrayfire-full-3.8.2.tar.bz2"],
)

# Depend on zlib (a non-bazel project, built manually in 3rdparty/zlib.BUILD)
http_archive(
    name = "zlib.c",
    build_file = "//3rdparty:zlib.BUILD",
    sha256 = "91844808532e5ce316b3c010929493c0244f3d37593afd6de04f71821d5136d9",
    strip_prefix = "zlib-1.2.12",
    urls = ["https://zlib.net/zlib-1.2.12.tar.gz"],
)


# Depends on GoogleTest
http_archive(
  name = "com_google_googletest",
  urls = ["https://github.com/google/googletest/archive/15460959cbbfa20e66ef0b5ab497367e47fc0a04.zip"],
  strip_prefix = "googletest-15460959cbbfa20e66ef0b5ab497367e47fc0a04",
)

# Setup rules_foreign_cc (CMake integration)
http_archive(
    name = "rules_foreign_cc",
    strip_prefix = "rules_foreign_cc-8d540605805fb69e24c6bf5dc885b0403d74746a", # 0.9.0
    url = "https://github.com/bazelbuild/rules_foreign_cc/archive/8d540605805fb69e24c6bf5dc885b0403d74746a.tar.gz",
)

load("@rules_foreign_cc//foreign_cc:repositories.bzl", "rules_foreign_cc_dependencies")

rules_foreign_cc_dependencies()

# Setup Rust rules
http_archive(
    name = "rules_rust",
    sha256 = "6bfe75125e74155955d8a9854a8811365e6c0f3d33ed700bc17f39e32522c822",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_rust/releases/download/0.9.0/rules_rust-v0.9.0.tar.gz",
        "https://github.com/bazelbuild/rules_rust/releases/download/0.9.0/rules_rust-v0.9.0.tar.gz",
    ],
)

load("@rules_rust//rust:repositories.bzl", "rules_rust_dependencies", "rust_register_toolchains")

rules_rust_dependencies()

# Note: version and edition can be specified globally here
rust_register_toolchains(version = "1.63.0", edition="2018")

load("@rules_rust//crate_universe:repositories.bzl", "crate_universe_dependencies")

crate_universe_dependencies()

# Define and load rust dependencies
load("@rules_rust//crate_universe:defs.bzl", "crates_repository", "crate")

crates_repository(
    name = "crate_index",
    cargo_lockfile = "//hello-rs:Cargo.Bazel.lock",
    lockfile = "//hello-rs:cargo-bazel-lock.json",
    packages = {
        "env_logger": crate.spec(
            version = "0.9.0",
        ),
        "log": crate.spec(
            version = "0.4.17"
        ),
    },
)

load("@crate_index//:defs.bzl", "crate_repositories")

crate_repositories()
