workspace(name = "helloworld")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Depend on com_google_protobuf (a bazel project)
http_archive(
      name = "com_google_protobuf",
      url = "https://github.com/protocolbuffers/protobuf/archive/refs/tags/v21.5.tar.gz",
      sha256 = "4a7e87e4166c358c63342dddcde6312faee06ea9d5bb4e2fa87d3478076f6639",
      strip_prefix = "protobuf-21.5",
)
load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")
protobuf_deps()

# Depend on zlib (a non-bazel project, built manually in 3rdparty/zlib.BUILD)
http_archive(
    name = "zlib.c",
    build_file = "//3rdparty:zlib.BUILD",
    sha256 = "91844808532e5ce316b3c010929493c0244f3d37593afd6de04f71821d5136d9",
    strip_prefix = "zlib-1.2.12",
    urls = ["https://zlib.net/zlib-1.2.12.tar.gz"],
)

# Depends on GoogleTest
http_archive(
  name = "com_google_googletest",
  urls = ["https://github.com/google/googletest/archive/15460959cbbfa20e66ef0b5ab497367e47fc0a04.zip"],
  strip_prefix = "googletest-15460959cbbfa20e66ef0b5ab497367e47fc0a04",
)

