workspace(name = "helloworld")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Depends on GoogleTest
http_archive(
  name = "com_google_googletest",
  urls = ["https://github.com/google/googletest/archive/15460959cbbfa20e66ef0b5ab497367e47fc0a04.zip"],
  strip_prefix = "googletest-15460959cbbfa20e66ef0b5ab497367e47fc0a04",
)
